### ISSUE TITLE
Everglades_ROME_SPI_GEN for windows

### ISSUE THREAD

**Issue by nschuetz1311** [MicrochipTech/CPGZephyrDocs#7]
Is there also an Everglades_ROME_SPI_GEN.exe available to generate the "spi_image.bin" under windows for the MEC152x or is it just available for Linux systems?

**Comment by scottwcpg** [comment]
@nschuetz1311 Added Windows version of MEC152x SPI image generator.

**Comment by nschuetz1311** [comment]
@scottwcpg Thank you  :)
